version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - "8080:80"

  gunicorn:
    build: .
    environment:
      - WORKERS=4
      - PORT=8000
    ports:
      - "8000:8000"
